// Code generated by SQLBoiler 4.3.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GorpMigrations string
	Message        string
}{
	GorpMigrations: "gorp_migrations",
	Message:        "message",
}
